[project]
name = "task-cli"
version = "0.10.0-rc0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Chris Nd", email = "50488760+chris-nd@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
task-cli = "task_cli.cli:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "commitizen>=4.18.1",
]
docs = [
    "sphinx>=9.1.0",
]
tests = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "uv"
update_changelog_on_bump = true
