name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install sphinx furo

      - name: Générer la documentation HTML
        run: |
          cd docs
          make html
          touch build/html/.nojekyll

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
